modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="iceandfire"
type="required"
versionRange="[${ice_and_fire_ce_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="spartan_weaponry_unofficial"
type="required"
versionRange="[${spartan_weaponry_unofficial_version},)"
ordering="AFTER"
side="BOTH"
